server:
  port: 8001

spring:
  application:
    name: api

  datasource:
    url: jdbc:mysql://localhost:3306/api?useSSL=false&serverTimeZone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    org.springframework.security: DEBUG

app:
  jwt-secret: xOT7PRZlYib4In7rxqVyhM9qNYv4LlCam76H2CHYWOY=
  jwt-expiration-milliseconds: 604800000
